### ISSUE TITLE
Yuyu not visible

### ISSUE THREAD

**Issue by kubeworkz** [btechpt/yuyu_dashboard#1]
Hi:
Great project btw:
Where should I be seeing Yuyu within Openstack? I've got Yuyu and the Yuyu_dashboard installed per the instructions. Do you have maybe a screenshot or something?
Just a note: I installed using Ubuntu Microstack. I can't seem to find the password for rabbitmq.
Cheers, Dave

**Comment by irfanpule** [comment]
Hi @kubeworkz 

if you have successfully installed, there should be a billing menu in the admin.  All Yuyu features are on the billing menu.

For detail usage, see here
https://opensource.btech.id/yuyu/price/

**Comment by kubeworkz** [comment]
Thanks - also found the rabbitmq transport url. I think I messed up the symbolic links to the dashboard files. Microstack puts horizon in a few spots:
1) `/var/snap/microstack/common/var/horizon/static` (static root)
2) `/var/snap/microstack/common/etc/horizon (containg /horizon.conf.d  /local_settings.d  /uwsgi)` When it asks for the horizon path when creating the sym links I'm not sure what to enter.

**Comment by kubeworkz** [comment]
Update: Microstack is installed via snap so the file system it resides on is read-only, hence I can't create the symlinks. It uses squashfs. I'll try unsquashing and attempt the symlinks. 

btw: The horizon root is in: `/snap/microstack/current/lib/python3.8/site-packages`

**Comment by irfanpule** [comment]
we have never tried on horizon microstack.  So we'll try it, but if you've succeeded, don't forget to inform here 😊
